/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_sprintf.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(_f_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %f";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %f";
  float n = 158;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %f";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_default_negative_num) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %f";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_negative_num_and_calculate) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten:  %f + %2.4f";
  double n1 = 625197265107228.6157297192;
  double n2 = -6793820.1640528;
  sprintf(expected, format, n1, n2);
  s21_sprintf(res, format, n1, n2);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2),
                   s21_sprintf(res, format, n1, n2));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_default) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %f";
  float n = 235;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_static_default_2) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %f";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_static_default_3) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %f";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_static_default_negative_num) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %f";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_dynamic_void_str) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_void_str) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_dynamic_null_pattern) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %f";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_null_pattern) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %f";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_static_with_a_few_pattern_and_calculate) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %f - %f + (%f * %f)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_f_dynamic_with_a_few_pattern_and_calculate_flags_minus_0) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3f - %6f + (%0f * %.8f)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_with_a_few_pattern_and_calculate_flags_minus_0) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3f - %6f + (%0f * %.8f)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_f_static_flags_and_width) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %+023.8f";
  double n = 625108832710.1537816391736153;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_dynamic_flags_and_width) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %+023.8f";
  double n = 625108832710.1537816391736153;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_flags_and_width_2) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3.10f";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_f_dynamic_flags_and_width_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3.10f";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_flags_calculate_width_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10f - %#.2f * (3 - %0.0f(%-2f))";
  double n1 = 625108832710;
  double n2 = 725.71982539;
  double n3 = 3;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_flags_calculate_width_few_pattern_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %*.10f - %#.2f * (3 - %*.0f(%-2f))";
  double n1 = 6251088.32710;
  double n2 = 725.71982539;
  double n3 = 3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, 2, n1, n2, 5, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, 5, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, 5, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, 5, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_dynamic_flags_calculate_width_few_pattern_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10f - %#.1f * (5.3452 - % 0f(%-.02f))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_flags_calculate_width_few_pattern_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %-3.10f - %#.1f * (5.3452 - % 0f(%-.02f))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_f_dynamic_mod) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: % .10Lf - %0Lf * (5.3452 - % 0Lf(%-.02Lf))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_f_static_mod) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: % .10Lf - %0Lf * (5.3452 - % 0Lf(%-.02Lf))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_f_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2f + %-2.f) * % 3.0f - %+.3f";
  float n1 = 725;
  float n2 = 17.1;
  float n3 = 51;
  float n4 = 0.1;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "kitty %c";
  char c = '!';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_static_default) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "kitty %c";
  char c = '!';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
}
END_TEST

START_TEST(_c_static_default_2) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "kitty %c";
  char c = '\n';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
}
END_TEST

START_TEST(_c_static_default_3) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "%c";
  char c = '\n';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
}
END_TEST

START_TEST(_c_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "kitty %c";
  char c = '\n';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "%c";
  char c = '\n';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_dynamic_zero_sym) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "kitty %c";
  char c = '\0';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_static_zero_sym) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "kitty %c";
  char c = '\0';
  sprintf(expected, format, c);
  s21_sprintf(res, format, c);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c), s21_sprintf(res, format, c));
}
END_TEST

START_TEST(_c_dynamic_a_few_pattern_and_width) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%-4c%c kitty %c %c%c";
  char c1 = '^';
  char c2 = '!';
  sprintf(expected, format, c1, c1, c2, c1, c1);
  s21_sprintf(res, format, c1, c1, c2, c1, c1);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c1, c1, c2, c1, c1),
                   s21_sprintf(res, format, c1, c1, c2, c1, c1));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_static_a_few_pattern_and_width) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%-4c%c kitty %c %c%c";
  char c1 = '^';
  char c2 = '!';
  sprintf(expected, format, c1, c1, c2, c1, c1);
  s21_sprintf(res, format, c1, c1, c2, c1, c1);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c1, c1, c2, c1, c1),
                   s21_sprintf(res, format, c1, c1, c2, c1, c1));
}
END_TEST

START_TEST(_c_dynamic_a_few_pattern_and_width_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%-*c%c kitty %c %*c%c";
  char c1 = '^';
  char c2 = '!';
  sprintf(expected, format, c1, 5, c1, c2, c1, 5, c1);
  s21_sprintf(res, format, c1, 5, c1, c2, c1, 5, c1);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c1, c1, c2, c1, c1),
                   s21_sprintf(res, format, c1, 5, c1, c2, c1, 5, c1));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_c_static_a_few_pattern_and_width_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%-*c%c kitty %c %*c%c";
  char c1 = '^';
  char c2 = '!';
  sprintf(expected, format, c1, 5, c1, c2, c1, 5, c1);
  s21_sprintf(res, format, c1, 5, c1, c2, c1, 5, c1);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, c1, c1, c2, c1, c1),
                   s21_sprintf(res, format, c1, 5, c1, c2, c1, 5, c1));
}
END_TEST

START_TEST(_d_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %d";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_d_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %d";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_d_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%d";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_d_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%d";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_d_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%*d";
  int n = 725;
  sprintf(expected, format, 2, n);
  s21_sprintf(res, format, 2, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n),
                   s21_sprintf(res, format, 2, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_d_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%*d";
  int n = 725;
  sprintf(expected, format, 2, n);
  s21_sprintf(res, format, 2, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n),
                   s21_sprintf(res, format, 2, n));
}
END_TEST

START_TEST(_d_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*d + %2.4d) * % 3.0d - %.3d";
  int n1 = 725;
  int n2 = 172;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_d_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2d + %-2.d) * % 3.0d - %+.3d";
  int n1 = 725;
  int n2 = 171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_d_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hd + %0hd) * %3.0ld - %-.3hd";
  int n1 = 725;
  int n2 = 175;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %i";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %i";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_i_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%i";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%i";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_i_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%*i";
  int n = 725;
  sprintf(expected, format, 2, n);
  s21_sprintf(res, format, 2, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n),
                   s21_sprintf(res, format, 2, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%*i";
  int n = 725;
  sprintf(expected, format, 2, n);
  s21_sprintf(res, format, 2, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n),
                   s21_sprintf(res, format, 2, n));
}
END_TEST

START_TEST(_i_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*i + %2.4i) * % 3.0i - %.3i";
  int n1 = 725;
  int n2 = 171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2i + %-2.i) * % 3.0i - %+.3i";
  int n1 = 725;
  int n2 = 175;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_i_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hi + %0hi) * %3.0li - %-.3hi";
  int n1 = 14;
  int n2 = 171;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_percent_and_other) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hd + %%) - %-.3li";
  int n1 = 14;
  long int n2 = 0;
  sprintf(expected, format, n1, n2);
  s21_sprintf(res, format, n1, n2);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2),
                   s21_sprintf(res, format, n1, n2));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_percent) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  sprintf(expected, "%%");
  s21_sprintf(res, "%%");
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, "%%"), s21_sprintf(res, "%%"));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_percent_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  sprintf(expected, "%% %% %% %%");
  s21_sprintf(res, "%% %% %% %%");
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, "%% %% %% %%"),
                   s21_sprintf(res, "%% %% %% %%"));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %s";
  char *str = "meow !";
  sprintf(expected, format, str);
  s21_sprintf(res, format, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, str),
                   s21_sprintf(res, format, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %s %s %s";
  char *str = "meow !";
  sprintf(expected, format, str, str, str);
  s21_sprintf(res, format, str, str, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, str, str, str),
                   s21_sprintf(res, format, str, str, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_flags_width) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %-10s";
  char *str = "meow !";
  sprintf(expected, format, str);
  s21_sprintf(res, format, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, str),
                   s21_sprintf(res, format, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_accuracy) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %.1s";
  char *str = "meow !";
  sprintf(expected, format, str);
  s21_sprintf(res, format, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, str),
                   s21_sprintf(res, format, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_accuracy_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %.*s";
  char *str = "meow !";
  sprintf(expected, format, 3, str);
  s21_sprintf(res, format, 3, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 3, str),
                   s21_sprintf(res, format, 3, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_flags_width_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %*s";
  char *str = "meow !";
  sprintf(expected, format, 2, str);
  s21_sprintf(res, format, 2, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, str),
                   s21_sprintf(res, format, 2, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_s_accuracy_and_width) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "what does the kitten say? %10.3s";
  char *str = "meow";
  sprintf(expected, format, str);
  s21_sprintf(res, format, str);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, str),
                   s21_sprintf(res, format, str));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %x";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_x_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%x";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%x";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_x_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%x";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%x";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_x_static_default_4) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%#x";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_x_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*x + %2.4x) * %3.0x - %.3x";
  int n1 = 725;
  int n2 = 171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2x + %-2.x) * %3.0x - %.3x";
  int n1 = -725;
  int n2 = -171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hx + %0hx) * %3.0lx - %-.3hx";
  int n1 = -725;
  int n2 = 171;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_x_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%#.5hx + %0hx) * %#lx - %-.3hx";
  int n1 = -725;
  int n2 = 1741;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %X";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_X_1_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%X";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%X";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_X_1_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%X";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%X";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_X_1_static_default_4) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%#X";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_X_1_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*X + %2.4X) * %3.0x - %.3X";
  int n1 = 725;
  int n2 = 170;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2X + %-2.X) * %3.0X - %.3X";
  int n1 = -725;
  int n2 = 174;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hX + %0hX) * %3.0lX - %-.3hX";
  int n1 = -725;
  int n2 = 179;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_X_1_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%#.5hX + %0hX) * %#lX - %-.3hX";
  int n1 = -725;
  int n2 = 176;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %o";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_o_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%o";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%o";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_o_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%o";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%o";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_o_static_default_4) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%#o";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_o_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*o + %2.4o) * %3.0o - %.3o";
  int n1 = 725;
  int n2 = 1761;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2o + %-2.o) * %3.0o - %.3o";
  int n1 = -725;
  int n2 = 17129;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0ho + %0ho) * %3.0lo - %-.*ho";
  int n1 = -725;
  int n2 = 172;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, 5, n4);
  s21_sprintf(res, format, n1, n2, n3, 5, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, 5, n4),
                   s21_sprintf(res, format, n1, n2, n3, 5, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_o_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%#.5ho + %0ho) * %#lo - %-.3ho";
  int n1 = -725;
  int n2 = 171;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %u";
  int n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_u_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%u";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%u";
  int n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_u_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%u";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%u";
  int n = -725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_u_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*u + %2.4u) * %3.0u - %.3u";
  int n1 = 725;
  int n2 = 171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2u + %-2.u) * %3.0u - %.3u";
  int n1 = -725;
  int n2 = 171;
  int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0hu + %0hu) * %3.0lu - %-.*hu";
  int n1 = -725;
  int n2 = 17131;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, 5, n4);
  s21_sprintf(res, format, n1, n2, n3, 5, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, 5, n4),
                   s21_sprintf(res, format, n1, n2, n3, 5, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_u_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.5hu + %0hu) * %lu - %-.3hu";
  int n1 = -725;
  int n2 = 170;
  long int n3 = 51;
  int n4 = 0;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_n_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  int res_buff;
  int expected_buff;
  char *format = "%n";
  s21_sprintf(res, format, &res_buff);
  sprintf(expected, format, &expected_buff);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(res_buff, expected_buff);
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_n_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  int res_buff;
  int expected_buff;
  char *format = "meow meow meow%n";
  s21_sprintf(res, format, &res_buff);
  sprintf(expected, format, &expected_buff);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(res_buff, expected_buff);
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_n_zero) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  int res_buff;
  int expected_buff;
  char *format = "\n%n";
  s21_sprintf(res, format, &res_buff);
  sprintf(expected, format, &expected_buff);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(res_buff, expected_buff);
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %e";
  double n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %e";
  double n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_e_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%e";
  double n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%e";
  double n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_e_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%e";
  double n = -17.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%e";
  double n = -17.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_e_static_default_4) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%#e";
  double n = 7.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_e_dynamic_default_4) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%#e";
  double n = 7.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*e + %2.4e) + %3.0e - %.3e";
  double n1 = 3525;
  double n2 = 164.1;
  double n3 = 53452.42420;
  double n4 = 0.1;
  sprintf(expected, format, 1, n1, n2, n3, n4);
  s21_sprintf(res, format, 1, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 1, n1, n2, n3, n4),
                   s21_sprintf(res, format, 1, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2e + %-2.e) * %3.0e - %.3e";
  double n1 = -228;
  double n2 = 838.995;
  double n3 = 5124683.199999;
  double n4 = 0.0;
  sprintf(expected, format, 1, n1, n2, n3, n4);
  s21_sprintf(res, format, 1, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 1, n1, n2, n3, n4),
                   s21_sprintf(res, format, 1, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0Le + %0Le) * %3.0Le - %-.3Le";
  long double n1 = -725;
  long double n2 = 838.995;
  long double n3 = 5124683.199999;
  long double n4 = 0.1;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_e_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%#.5Le + %0e) * %#Le - %-.3Le";
  long double n1 = -725;
  double n2 = 17.1;
  long double n3 = 51;
  long double n4 = 0.1;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %E";
  double n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_static_default) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %E";
  double n = 7;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_E_1_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%E";
  double n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_static_default_2) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%E";
  double n = 725;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_E_1_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%E";
  double n = -17.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_static_default_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%E";
  double n = -17.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_E_1_static_default_4) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "%#E";
  double n = 7.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_E_1_dynamic_default_4) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%#E";
  double n = 7.25;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*E + %2.4E) + %3.0E - %.3E";
  double n1 = 3525;
  double n2 = 164.1;
  double n3 = 53452.42420;
  double n4 = 0.1;
  sprintf(expected, format, 1, n1, n2, n3, n4);
  s21_sprintf(res, format, 1, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 1, n1, n2, n3, n4),
                   s21_sprintf(res, format, 1, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_dynamic_width_few_pattern_calculate_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2E + %-2.E) * %3.0E - %.3E";
  double n1 = -228;
  double n2 = 838.995;
  double n3 = 5124683.199999;
  double n4 = 0.0;
  sprintf(expected, format, 1, n1, n2, n3, n4);
  s21_sprintf(res, format, 1, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 1, n1, n2, n3, n4),
                   s21_sprintf(res, format, 1, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_dynamic_width_few_pattern_calculate_lenght) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%.0LE + %0LE) * %3.0LE - %-.3LE";
  long double n1 = -725;
  long double n2 = 838.995;
  long double n3 = 5124683.199999;
  long double n4 = 0.1;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_E_1_dynamic_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%#.5LE + %0E) * %#LE - %-.3LE";
  long double n1 = -725;
  double n2 = 17.1;
  long double n3 = 51;
  long double n4 = 0.1;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %g";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %g";
  float n = 158;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %g";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_default_negative_num) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %g";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_negative_num_and_calculate) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten:  %g + %2.4g";
  double n1 = 625197265107228.6157297192;
  double n2 = -6793820.1640528;
  sprintf(expected, format, n1, n2);
  s21_sprintf(res, format, n1, n2);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2),
                   s21_sprintf(res, format, n1, n2));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_default) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %g";
  float n = 235;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_static_default_2) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %g";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_static_default_3) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %g";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_static_default_negative_num) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %g";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_dynamic_void_str) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_void_str) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_dynamic_null_pattern) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %g";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_null_pattern) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %g";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_static_with_a_few_pattern_and_calculate) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %g - %g + (%g * %g)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_g_dynamic_with_a_few_pattern_and_calculate_flags_minus_0) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3g - %6g + (%0g * %.8g)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_with_a_few_pattern_and_calculate_flags_minus_0) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3g - %6g + (%0g * %.8g)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_g_dynamic_flags_and_width) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %+023.8Lg";
  long double n = 625108832710.1537816391736153;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_flags_and_width_2) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3.10g";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_g_dynamic_flags_and_width_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3.10g";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_flags_calculate_width_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10g - %#.2g * (3 - %0.0g(%-2g))";
  double n1 = 625108832710;
  double n2 = 725.71982539;
  double n3 = 3;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_flags_calculate_width_few_pattern_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %*.10g - %#.2g * (3 - %*.0g(%-2g))";
  double n1 = 62088.32710;
  double n2 = 725.72539;
  double n3 = 420;
  double n4 = 22710.363123;
  sprintf(expected, format, 2, n1, n2, 5, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, 5, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, 5, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, 5, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_dynamic_flags_calculate_width_few_pattern_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10g - %#.1g * (5.3452 - % 0g(%-.02g))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_flags_calculate_width_few_pattern_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %-3.10g - %#.1g * (5.3452 - % 0g(%-.02g))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_g_dynamic_mod) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: % .10Lg - %0Lg * (5.3452 - % 0Lg(%-.02Lg))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_g_static_mod) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: % .10Lg - %0Lg * (5.3452 - % 0Lg(%-.02Lg))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_g_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2g + %-2.g) * % 3.g - %+g";
  double n1 = 1725;
  double n2 = 17.1;
  double n3 = 5251;
  double n4 = 0.0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_default) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %G";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_default_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %G";
  float n = 158;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_default_3) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %G";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_default_negative_num) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %G";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_negative_num_and_calculate) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten:  %G + %2.4G";
  double n1 = 625197265107228.6157297192;
  double n2 = -6793820.1640528;
  sprintf(expected, format, n1, n2);
  s21_sprintf(res, format, n1, n2);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2),
                   s21_sprintf(res, format, n1, n2));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_default) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %G";
  float n = 235;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_static_default_2) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %G";
  float n = 7.77;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_static_default_3) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %G";
  double n = 679382083.1640973528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_static_default_negative_num) {
  char res[150] = "counter";
  char expected[150] = "counter";
  char *format = " kitten: %G";
  double n = -6793820.1640528;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_dynamic_null_pattern) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %G";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_null_pattern) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %G";
  float n = 0.0;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_static_with_a_few_pattern_and_calculate) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %G - %G + (%G * %G)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_G_1_dynamic_with_a_few_pattern_and_calculate_flags_minus_0) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3G - %6G + (%0G * %.8G)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_with_a_few_pattern_and_calculate_flags_minus_0) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3G - %6G + (%0G * %.8G)";
  float n1 = 127.46304;
  float n2 = 1.2;
  float n3 = 24.97;
  float n4 = 56;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_G_1_static_flags_and_width) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %+023.8G";
  double n = 625108832710.1537816391736153;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_dynamic_flags_and_width) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %+023.8LG";
  long double n = 625108832710.1537816391736153;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_flags_and_width_2) {
  char res[150] = "";
  char expected[150] = "";
  char *format = "counter kitten: %-3.10G";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
}
END_TEST

START_TEST(_G_1_dynamic_flags_and_width_2) {
  char *res = (char *)calloc(sizeof(char), 100);
  char *expected = (char *)calloc(sizeof(char), 100);
  char *format = "counter kitten: %-3.10G";
  double n = 625108832710;
  sprintf(expected, format, n);
  s21_sprintf(res, format, n);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n), s21_sprintf(res, format, n));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_flags_calculate_width_few_pattern) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10G - %#.2G * (3 - %0.0G(%-2G))";
  double n1 = 625108832710;
  double n2 = 725.71982539;
  double n3 = 3;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_flags_calculate_width_few_pattern_2) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %*.10G - %#.2G * (3 - %*.0G(%-2G))";
  double n1 = 62088.32710;
  double n2 = 725.72539;
  double n3 = 420;
  double n4 = 22710.363123;
  sprintf(expected, format, 2, n1, n2, 5, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, 5, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, 5, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, 5, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_dynamic_flags_calculate_width_few_pattern_3) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: %-3.10g - %#.1g * (5.3452 - % 0g(%-.02g))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_flags_calculate_width_few_pattern_3) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: %-3.10G - %#.1G * (5.3452 - % 0G(%-.02G))";
  double n1 = 625108832710;
  double n2 = 0.71982539;
  double n3 = -3.0;
  double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_G_1_dynamic_mod) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: % .10LG - %0LG * (5.3452 - % 0LG(%-.02LG))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_G_1_static_mod) {
  char res[256] = "";
  char expected[256] = "";
  char *format = "counter kitten: % .10LG - %0LG * (5.3452 - % 0LG(%-.02LG))";
  long double n1 = 62510883.2710;
  long double n2 = 0.71982539;
  long double n3 = -3.0;
  long double n4 = 22710.361583123;
  sprintf(expected, format, n1, n2, n3, n4);
  s21_sprintf(res, format, n1, n2, n3, n4);
  ck_assert_str_eq(expected, res);
  ck_assert_int_eq(sprintf(expected, format, n1, n2, n3, n4),
                   s21_sprintf(res, format, n1, n2, n3, n4));
}
END_TEST

START_TEST(_G_1_dynamic_width_few_pattern_calculate) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "counter kitten: (%*.2G + %-2.G) * % 3.G - %+G";
  double n1 = 1725;
  double n2 = 17.1;
  double n3 = 5251;
  double n4 = 0.0;
  sprintf(expected, format, 2, n1, n2, n3, n4);
  s21_sprintf(res, format, 2, n1, n2, n3, n4);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, 2, n1, n2, n3, n4),
                   s21_sprintf(res, format, 2, n1, n2, n3, n4));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_p_int_default) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%p";
  int pointer = 420;
  sprintf(expected, format, &pointer);
  s21_sprintf(res, format, &pointer);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, &pointer),
                   s21_sprintf(res, format, &pointer));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_p_double) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%p";
  double pointer = 5462.725420;
  sprintf(expected, format, &pointer);
  s21_sprintf(res, format, &pointer);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, &pointer),
                   s21_sprintf(res, format, &pointer));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_p_char) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%p";
  char pointer = 'w';
  sprintf(expected, format, &pointer);
  s21_sprintf(res, format, &pointer);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, &pointer),
                   s21_sprintf(res, format, &pointer));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

START_TEST(_p_float) {
  char *res = (char *)calloc(sizeof(char), 256);
  char *expected = (char *)calloc(sizeof(char), 256);
  char *format = "%p";
  float pointer = -0.0;
  sprintf(expected, format, &pointer);
  s21_sprintf(res, format, &pointer);
  ck_assert_str_eq(res, expected);
  ck_assert_int_eq(sprintf(expected, format, &pointer),
                   s21_sprintf(res, format, &pointer));
  if (res) free(res);
  if (expected) free(expected);
}
END_TEST

Suite *sprintf_suite() {
  Suite *s = suite_create("Tests for sprintf");
  TCase *tc1_1 = tcase_create("f");
  TCase *tc1_2 = tcase_create("c");
  TCase *tc1_3 = tcase_create("d");
  TCase *tc1_4 = tcase_create("i");
  TCase *tc1_5 = tcase_create("percent");
  TCase *tc1_6 = tcase_create("s");
  TCase *tc1_7 = tcase_create("x");
  TCase *tc1_8 = tcase_create("X_1");
  TCase *tc1_9 = tcase_create("o");
  TCase *tc1_10 = tcase_create("u");
  TCase *tc1_11 = tcase_create("n");
  TCase *tc1_12 = tcase_create("e");
  TCase *tc1_13 = tcase_create("E_1");
  TCase *tc1_14 = tcase_create("g");
  TCase *tc1_15 = tcase_create("G_1");
  TCase *tc1_16 = tcase_create("p");

  suite_add_tcase(s, tc1_1);
  tcase_add_test(tc1_1, _f_dynamic_default);
  tcase_add_test(tc1_1, _f_dynamic_default_2);
  tcase_add_test(tc1_1, _f_dynamic_default_3);
  tcase_add_test(tc1_1, _f_dynamic_default_negative_num);
  tcase_add_test(tc1_1, _f_dynamic_negative_num_and_calculate);
  tcase_add_test(tc1_1, _f_static_default);
  tcase_add_test(tc1_1, _f_static_default_2);
  tcase_add_test(tc1_1, _f_static_default_3);
  tcase_add_test(tc1_1, _f_static_default_negative_num);
  tcase_add_test(tc1_1, _f_dynamic_void_str);
  tcase_add_test(tc1_1, _f_static_void_str);
  tcase_add_test(tc1_1, _f_dynamic_null_pattern);
  tcase_add_test(tc1_1, _f_static_null_pattern);
  tcase_add_test(tc1_1, _f_static_with_a_few_pattern_and_calculate);
  tcase_add_test(tc1_1,
                 _f_dynamic_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_1,
                 _f_static_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_1, _f_static_flags_and_width);
  tcase_add_test(tc1_1, _f_dynamic_flags_and_width);
  tcase_add_test(tc1_1, _f_static_flags_and_width_2);
  tcase_add_test(tc1_1, _f_dynamic_flags_and_width_2);
  tcase_add_test(tc1_1, _f_dynamic_flags_calculate_width_few_pattern);
  tcase_add_test(tc1_1, _f_dynamic_flags_calculate_width_few_pattern_2);
  tcase_add_test(tc1_1, _f_dynamic_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_1, _f_static_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_1, _f_dynamic_mod);
  tcase_add_test(tc1_1, _f_static_mod);
  tcase_add_test(tc1_1, _f_dynamic_width_few_pattern_calculate);
  suite_add_tcase(s, tc1_2);
  tcase_add_test(tc1_2, _c_dynamic_default);
  tcase_add_test(tc1_2, _c_static_default);
  tcase_add_test(tc1_2, _c_static_default_2);
  tcase_add_test(tc1_2, _c_static_default_3);
  tcase_add_test(tc1_2, _c_dynamic_default_2);
  tcase_add_test(tc1_2, _c_dynamic_default_3);
  tcase_add_test(tc1_2, _c_dynamic_zero_sym);
  tcase_add_test(tc1_2, _c_static_zero_sym);
  tcase_add_test(tc1_2, _c_dynamic_a_few_pattern_and_width);
  tcase_add_test(tc1_2, _c_static_a_few_pattern_and_width);
  tcase_add_test(tc1_2, _c_dynamic_a_few_pattern_and_width_2);
  tcase_add_test(tc1_2, _c_static_a_few_pattern_and_width_2);
  suite_add_tcase(s, tc1_3);
  tcase_add_test(tc1_3, _d_dynamic_default);
  tcase_add_test(tc1_3, _d_static_default);
  tcase_add_test(tc1_3, _d_dynamic_default_2);
  tcase_add_test(tc1_3, _d_static_default_2);
  tcase_add_test(tc1_3, _d_dynamic_default_3);
  tcase_add_test(tc1_3, _d_static_default_3);
  tcase_add_test(tc1_3, _d_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_3, _d_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_3, _d_dynamic_width_few_pattern_calculate_lenght);
  suite_add_tcase(s, tc1_4);
  tcase_add_test(tc1_4, _i_dynamic_default);
  tcase_add_test(tc1_4, _i_static_default);
  tcase_add_test(tc1_4, _i_dynamic_default_2);
  tcase_add_test(tc1_4, _i_static_default_2);
  tcase_add_test(tc1_4, _i_dynamic_default_3);
  tcase_add_test(tc1_4, _i_static_default_3);
  tcase_add_test(tc1_4, _i_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_4, _i_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_4, _i_dynamic_width_few_pattern_calculate_lenght);
  suite_add_tcase(s, tc1_5);
  tcase_add_test(tc1_5, _percent_and_other);
  tcase_add_test(tc1_5, _percent);
  tcase_add_test(tc1_5, _percent_2);
  suite_add_tcase(s, tc1_6);
  tcase_add_test(tc1_6, _s_default);
  tcase_add_test(tc1_6, _s_default_2);
  tcase_add_test(tc1_6, _s_flags_width);
  tcase_add_test(tc1_6, _s_accuracy);
  tcase_add_test(tc1_6, _s_accuracy_2);
  tcase_add_test(tc1_6, _s_flags_width_2);
  tcase_add_test(tc1_6, _s_accuracy_and_width);
  suite_add_tcase(s, tc1_7);
  tcase_add_test(tc1_7, _x_static_default);
  tcase_add_test(tc1_7, _x_dynamic_default_2);
  tcase_add_test(tc1_7, _x_static_default_2);
  tcase_add_test(tc1_7, _x_dynamic_default_3);
  tcase_add_test(tc1_7, _x_static_default_3);
  tcase_add_test(tc1_7, _x_static_default_4);
  tcase_add_test(tc1_7, _x_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_7, _x_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_7, _x_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_7, _x_dynamic_few_pattern);
  suite_add_tcase(s, tc1_8);
  tcase_add_test(tc1_8, _X_1_static_default);
  tcase_add_test(tc1_8, _X_1_dynamic_default_2);
  tcase_add_test(tc1_8, _X_1_static_default_2);
  tcase_add_test(tc1_8, _X_1_dynamic_default_3);
  tcase_add_test(tc1_8, _X_1_static_default_3);
  tcase_add_test(tc1_8, _X_1_static_default_4);
  tcase_add_test(tc1_8, _X_1_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_8, _X_1_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_8, _X_1_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_8, _X_1_dynamic_few_pattern);
  suite_add_tcase(s, tc1_9);
  tcase_add_test(tc1_9, _o_static_default);
  tcase_add_test(tc1_9, _o_dynamic_default_2);
  tcase_add_test(tc1_9, _o_static_default_2);
  tcase_add_test(tc1_9, _o_dynamic_default_3);
  tcase_add_test(tc1_9, _o_static_default_3);
  tcase_add_test(tc1_9, _o_static_default_4);
  tcase_add_test(tc1_9, _o_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_9, _o_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_9, _o_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_9, _o_dynamic_few_pattern);
  suite_add_tcase(s, tc1_10);
  tcase_add_test(tc1_10, _u_static_default);
  tcase_add_test(tc1_10, _u_dynamic_default_2);
  tcase_add_test(tc1_10, _u_static_default_2);
  tcase_add_test(tc1_10, _u_dynamic_default_3);
  tcase_add_test(tc1_10, _u_static_default_3);
  tcase_add_test(tc1_10, _u_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_10, _u_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_10, _u_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_10, _u_dynamic_few_pattern);
  suite_add_tcase(s, tc1_11);
  tcase_add_test(tc1_11, _n_default);
  tcase_add_test(tc1_11, _n_default_2);
  tcase_add_test(tc1_11, _n_zero);
  suite_add_tcase(s, tc1_12);
  tcase_add_test(tc1_12, _e_dynamic_default);
  tcase_add_test(tc1_12, _e_static_default);
  tcase_add_test(tc1_12, _e_dynamic_default_2);
  tcase_add_test(tc1_12, _e_static_default_2);
  tcase_add_test(tc1_12, _e_dynamic_default_3);
  tcase_add_test(tc1_12, _e_static_default_3);
  tcase_add_test(tc1_12, _e_static_default_4);
  tcase_add_test(tc1_12, _e_dynamic_default_4);
  tcase_add_test(tc1_12, _e_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_12, _e_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_12, _e_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_12, _e_dynamic_few_pattern);
  suite_add_tcase(s, tc1_13);
  tcase_add_test(tc1_13, _E_1_dynamic_default);
  tcase_add_test(tc1_13, _E_1_static_default);
  tcase_add_test(tc1_13, _E_1_dynamic_default_2);
  tcase_add_test(tc1_13, _E_1_static_default_2);
  tcase_add_test(tc1_13, _E_1_dynamic_default_3);
  tcase_add_test(tc1_13, _E_1_static_default_3);
  tcase_add_test(tc1_13, _E_1_static_default_4);
  tcase_add_test(tc1_13, _E_1_dynamic_default_4);
  tcase_add_test(tc1_13, _E_1_dynamic_width_few_pattern_calculate);
  tcase_add_test(tc1_13, _E_1_dynamic_width_few_pattern_calculate_2);
  tcase_add_test(tc1_13, _E_1_dynamic_width_few_pattern_calculate_lenght);
  tcase_add_test(tc1_13, _E_1_dynamic_few_pattern);
  suite_add_tcase(s, tc1_14);
  tcase_add_test(tc1_14, _g_dynamic_default);
  tcase_add_test(tc1_14, _g_dynamic_default_2);
  tcase_add_test(tc1_14, _g_dynamic_default_3);
  tcase_add_test(tc1_14, _g_dynamic_default_negative_num);
  tcase_add_test(tc1_14, _g_dynamic_negative_num_and_calculate);
  tcase_add_test(tc1_14, _g_static_default);
  tcase_add_test(tc1_14, _g_static_default_2);
  tcase_add_test(tc1_14, _g_static_default_3);
  tcase_add_test(tc1_14, _g_static_default_negative_num);
  tcase_add_test(tc1_14, _g_dynamic_void_str);
  tcase_add_test(tc1_14, _g_static_void_str);
  tcase_add_test(tc1_14, _g_dynamic_null_pattern);
  tcase_add_test(tc1_14, _g_static_null_pattern);
  tcase_add_test(tc1_14, _g_static_with_a_few_pattern_and_calculate);
  tcase_add_test(tc1_14,
                 _g_dynamic_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_14,
                 _g_static_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_14, _g_dynamic_flags_and_width);
  tcase_add_test(tc1_14, _g_static_flags_and_width_2);
  tcase_add_test(tc1_14, _g_dynamic_flags_and_width_2);
  tcase_add_test(tc1_14, _g_dynamic_flags_calculate_width_few_pattern);
  tcase_add_test(tc1_14, _g_dynamic_flags_calculate_width_few_pattern_2);
  tcase_add_test(tc1_14, _g_dynamic_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_14, _g_static_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_14, _g_dynamic_mod);
  tcase_add_test(tc1_14, _g_static_mod);
  tcase_add_test(tc1_14, _g_dynamic_width_few_pattern_calculate);
  suite_add_tcase(s, tc1_15);
  tcase_add_test(tc1_15, _G_1_dynamic_default);
  tcase_add_test(tc1_15, _G_1_dynamic_default_2);
  tcase_add_test(tc1_15, _G_1_dynamic_default_3);
  tcase_add_test(tc1_15, _G_1_dynamic_default_negative_num);
  tcase_add_test(tc1_15, _G_1_dynamic_negative_num_and_calculate);
  tcase_add_test(tc1_15, _G_1_static_default);
  tcase_add_test(tc1_15, _G_1_static_default_2);
  tcase_add_test(tc1_15, _G_1_static_default_3);
  tcase_add_test(tc1_15, _G_1_static_default_negative_num);
  tcase_add_test(tc1_15, _G_1_dynamic_null_pattern);
  tcase_add_test(tc1_15, _G_1_static_null_pattern);
  tcase_add_test(tc1_15, _G_1_static_with_a_few_pattern_and_calculate);
  tcase_add_test(tc1_15,
                 _G_1_dynamic_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_15,
                 _G_1_static_with_a_few_pattern_and_calculate_flags_minus_0);
  tcase_add_test(tc1_15, _G_1_static_flags_and_width);
  tcase_add_test(tc1_15, _G_1_dynamic_flags_and_width);
  tcase_add_test(tc1_15, _G_1_static_flags_and_width_2);
  tcase_add_test(tc1_15, _G_1_dynamic_flags_and_width_2);
  tcase_add_test(tc1_15, _G_1_dynamic_flags_calculate_width_few_pattern);
  tcase_add_test(tc1_15, _G_1_dynamic_flags_calculate_width_few_pattern_2);
  tcase_add_test(tc1_15, _G_1_dynamic_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_15, _G_1_static_flags_calculate_width_few_pattern_3);
  tcase_add_test(tc1_15, _G_1_dynamic_mod);
  tcase_add_test(tc1_15, _G_1_static_mod);
  tcase_add_test(tc1_15, _G_1_dynamic_width_few_pattern_calculate);
  suite_add_tcase(s, tc1_16);
  tcase_add_test(tc1_16, _p_int_default);
  tcase_add_test(tc1_16, _p_double);
  tcase_add_test(tc1_16, _p_char);
  tcase_add_test(tc1_16, _p_float);

  return s;
}
